STYLER-Inc/styler-rest-framework

- .coveragerc
- requirements.txt
- setup.py
- styler_rest_framework/exceptions/business/__init__.py
- styler_rest_framework/exceptions/services/__init__.py
- Adding exceptions to the framework
- Fixing coverage report
- Moving requirements to `setup.py`
> Adding exceptions

- styler_rest_framework/business/__init__.py
- tests/business/test_session_aware.py
Adding logic to the business layer.
> Adding business layer

- styler_rest_framework/controllers/__init__.py
- tests/controllers/test_base_controller.py
> Adding the controller layer

- requirements_dev.txt
- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/exceptions/business/__init__.py
- styler_rest_framework/exceptions/services/__init__.py
- styler_rest_framework/services/__init__.py
- tests/conftest.py
- tests/controllers/test_base_controller.py
- tests/exceptions/test_service_error.py
- tests/services/test_http_handler.py
- Adding the service layer to handle inter-service communication.
- Fixing exceptions for controllers
> Adding service layer

- styler_rest_framework/helpers/paginator.py
- tests/helpers/test_paginator.py
Adding the paginator helper used for pagination.
> Adding the Paginator

- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/controllers/request_scope.py
- styler_rest_framework/services/__init__.py
- styler_rest_framework/tracing/tracing.py
- tests/controllers/test_base_controller.py
- tests/controllers/test_request_scope.py
- tests/services/test_http_handler.py
- tests/tracing/test_tracing.py
- Adding the Tracing middleware to trace requests to Google Cloud Trace API.
- Integration with the service layer, sending requests through HTTPHandler is automatically using the current trace span.
- Adding RequestScope to handle general identity data (identity, request tracing, localization) inside the request scope.
Testing the tracing middleware is not done yet, and it might be quite challenging to do.
> Tracing middleware

- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/exceptions/services/__init__.py
- styler_rest_framework/services/__init__.py
- tests/controllers/test_base_controller.py
- tests/exceptions/test_service_error.py
Remove the dependency between custom service exceptions and the response.
> Service exception refactoring

- styler_rest_framework/business/__init__.py
- tests/business/test_session_aware.py
Close the session in case an exception is raised.
> Close session in session aware

- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/exceptions/business/__init__.py
- tests/controllers/test_base_controller.py
- Refactor on exception handling in the controller layer.
- Add a method to raise HTTPInternalServerError.
- Add an exception InternalError in the business layer
> Refactor exception handling

- setup.py
- styler_rest_framework/helpers/server_defaults.py
- styler_rest_framework/logging/__init__.py
- tests/helpers/test_server_defaults.py
- Adding cloud logging support.
- Adding helper functions to reduce boilerplate coding.
> Add logging

- styler_rest_framework/services/__init__.py
- tests/services/test_http_handler.py
Pass the header `Accept-Language` between services
> Pass localization between services

- setup.py
- styler_rest_framework/message/__init__.py
- styler_rest_framework/message/labels/validation.en.yml
- styler_rest_framework/message/labels/validation.ja.yml
- styler_rest_framework/validation/__init__.py
- tests/message/test_message.py
- tests/validation/test_validation.py
- Adding i18n support for module `message`
- Adding i18n support for module `validation`
> Add i18n support

- styler_rest_framework/helpers/migration.py
- tests/helpers/test_migration.py
Fix a bug which causing error in migration tool.
> Bug fix in migration tool

- styler_rest_framework/logging/__init__.py
Adding an optional parameter to force a sleep.
> Force sleep logging

- styler_rest_framework/logging/__init__.py
> Revert sleep time

- styler_rest_framework/controllers/__init__.py
- tests/controllers/test_base_controller.py
Changing the logging level for expected issues (from `error` to `warning`)
> Adjust the logging level in controllers

- styler_rest_framework/api/__init__.py
- styler_rest_framework/api/request_scope.py
- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/controllers/request_scope.py
- tests/api/test_request_scope.py
- tests/controllers/test_base_controller.py
Adding the new RequestScope, compatible with FastAPI.
> New request scope

- styler_rest_framework/helpers/aiohttp_defaults.py
- Add the optional parameter to set the service name in the error reporting.
- Add optional parameters to configure middlewares.
> Adding the service name to the error reporting

- styler_rest_framework/helpers/aiohttp_defaults.py
- styler_rest_framework/logging/error_reporting.py
Adding a generic error reporting for non-APIs
> Adding generic error reporting for non APIs

- styler_rest_framework/config/defaults.py
> Fix defaults

- requirements_dev.txt
- setup.py
- styler_rest_framework/helpers/fastapi_defaults.py
- styler_rest_framework/middlewares/fastapi/exception_middleware.py
- tests/helpers/test_fastapi_defaults.py
- tests/middlewares/test_exception_middleware.py
Adding the exception middleware for FastAPI.
> Add exception middleware

- styler_rest_framework/datasource/sqlalchemy/session.py
- tests/datasource/sqlalchemy/test_session.py
> Adding session handling

- styler_rest_framework/helpers/fastapi_defaults.py
> Patch localized error

- setup.py
- styler_rest_framework/crypto/aes.py
- tests/crypto/test_aes.py
Adding a crypto module to handle AES encryption.
> Add crypto module

- styler_rest_framework/crypto/aes.py
Iteration number was too high, causing performance issues.
> Change the iteration

- styler_rest_framework/api/responses.py
- styler_rest_framework/schemas/error.py
- tests/api/test_responses.py
Adding the a response helper to handle standard response codes.
> Response helpers

- styler_rest_framework/api/responses.py
- styler_rest_framework/controllers/__init__.py
- styler_rest_framework/exceptions/business/__init__.py
- styler_rest_framework/schemas/error.py
- tests/api/test_responses.py
- tests/controllers/test_base_controller.py
- Add error handling for conflict case
> add error handling for conflict case

- styler_rest_framework/api/responses.py
- styler_rest_framework/helpers/fastapi_defaults.py
- styler_rest_framework/schemas/error.py
- tests/api/test_responses.py
Adding a helper to handle standard error formats for FastAPI.
> Standard error formats for FastAPI

- styler_rest_framework/api/responses.py
- styler_rest_framework/schemas/error.py
- tests/api/test_responses.py
> Fix error format

- setup.py
- styler_rest_framework/api/request_scope.py
- styler_rest_framework/controllers/request_scope.py
- tests/api/test_request_scope.py
- tests/conftest.py
Fix problems caused by the new version of pyjwt
> Fix new pyjwt

- styler_rest_framework/crud/base.py
- tests/crud/test_base.py
* add crud base for Fast-api based service
* add tests
> Enhancement: add crud base for Fast-api based service

- .github/workflows/python-package.yml
- .gitignore
- tox.ini
> Changes in the ci

- styler_rest_framework/config/defaults.py
- styler_rest_framework/helpers/mailer.py
- styler_rest_framework/pubsub/publishers/messages/send_mail_message.py
- tests/helpers/test_mailer.py
- tests/pubsub/publishers/messages/test_send_mail.py
> Add mailer

- styler_rest_framework/api/responses.py
- styler_rest_framework/exceptions/services/__init__.py
- styler_rest_framework/services/__init__.py
- tests/api/test_responses.py
- tests/services/test_http_handler.py
Add 409 error in service errors and response handler.
> Add 409 error and tests

- .github/workflows/python-package.yml
- styler_rest_framework/pubsub/__init__.py
- tests/pubsub/test_message_router.py
- Change the ack of messages to only occur after the message is processed successfully
> Ack message

- styler_rest_framework/helpers/fastapi_defaults.py
Fix to the error reporting (FastAPI)
> Fix to the error reporting

- styler_rest_framework/services/__init__.py
> HTTPHandler: set identity as optional

- requirements_dev.txt
- setup.py
- styler_rest_framework/datasource/__init__.py
- styler_rest_framework/datasource/firestore.py
- tests/conftest.py
- tests/datasource/test_firestore.py
- tox.ini
[Move Firestore handler into Styler Rest Framework](https://styler.atlassian.net/browse/STYLER-1450)
* Add firestore handler in datasource folder
* Add tests
> STYLER-1450: Move Firestore handler into Styler Rest Framework

- styler_rest_framework/config/defaults.py
- styler_rest_framework/helpers/logme.py
- styler_rest_framework/pubsub/publishers/messages/logme_message.py
- tests/helpers/test_logme.py
- tests/pubsub/publishers/messages/test_logme.py
> Added helper - LogMe

- styler_rest_framework/api/authorization.py
- tests/api/test_authorization.py
> Add decorator for role

- styler_rest_framework/helpers/fastapi_defaults.py
- styler_rest_framework/middlewares/fastapi/auth_middleware.py
- Fix the OpenAPI generation in case there is no schema
- Handle authorization headers without bearer.
> Fixing Auth middleware and OpenAPI generation
